server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/u8_update?serverTimezone=Asia/Shanghai
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: false
logging:
  level:
    root: INFO
    com.zq.u8Patch.mapper: debug
crawl:
  patch:
    main: false
    detail: false
  sql-patch: false